CREATE TABLE "Subscriber" (
  "id" TEXT PRIMARY KEY,
  "email" TEXT NOT NULL UNIQUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "confirmed" BOOLEAN NOT NULL DEFAULT FALSE,
  "source" TEXT
);
